### ISSUE TITLE
Registro de Usuarios

### ISSUE THREAD

**Issue by hendaniel** [hendaniel/AppRenal#6]
* [ ] El sistema debe tener la capacidad de registrarse "a mano" o a través de cuentas externas ("google", "facebook").
* [ ] La aplicación debe traer toda la información del perfil y sus dietas.
* [ ] Se debe poder ver y cambiar de forma fácil los permisos que se le han otorgado previamente a la aplicación.
